pull_request_rules:

  - name: warn on conflicts
    conditions:
      - conflict
      - -draft  # filter-out GH draft PRs
      - -label="has conflicts"
    actions:
      # comment:
      #   message: This pull request is now in conflict... :(
      label:
        add: [ "has conflicts" ]

  - name: resolved conflicts
    conditions:
      - -conflict
      - label="has conflicts"
      - -draft  # filter-out GH draft PRs
      - -merged  # not merged yet
      - -closed
    actions:
      label:
        remove: [ "has conflicts" ]

  - name: update PR
    conditions:
      - -conflict
      - -draft  # filter-out GH draft PRs
      #- base=main  # apply only on master
      - -title~=(?i)wip  # skip all PR that title contains “WIP” (ignoring case)
      - "#approved-reviews-by>=1" # number of review approvals
    actions:
      update: {}

  - name: Ready to Go
    conditions:
      - -conflict
      - -draft  # filter-out GH draft PRs
      - -title~=(?i)wip  # skip all PR that title contains “WIP” (ignoring case)
      - "#approved-reviews-by>=1"  # number of review approvals
      - "#changes-requested-reviews-by=0"  # no requested changes
      - "#check-pending<=1"
      - "#check-failure<2"
    actions:
      label:
        add: [ "0:] Ready-To-Go" ]

  - name: Not ready yet
    conditions:
      - or:
        - draft  # filter-out GH draft PRs
        - title~=(?i)wip  # skip all PR that title contains “WIP” (ignoring case)
        - "#approved-reviews-by=0"  # number of review approvals
        - "#changes-requested-reviews-by>=1"  # no requested changes
        - "#check-failure>=3"
    actions:
      label:
        remove: [ "0:] Ready-To-Go" ]

  - name: add reviewer
    conditions:
      - -conflict  # skip if conflict
      - -draft  # filter-out GH draft PRs
      - "#approved-reviews-by<1"  # number of review approvals
      - "#review-requested<1"  # number of requested reviews
    actions:
      request_reviews:
        users:
          - Borda
        random_count: 1
